#!/bin/sh -e

# # Apache gets grumpy about PID files pre-existing
# rm -f /usr/local/apache2/logs/httpd.pid


# exec httpd -f "$@"

exec httpd \
  -f \
  -h /var/www/html \
  -p 3000
  
  #  \
  # -c /etc/httpd.conf
